### ISSUE TITLE
Keepalived License Issue

### ISSUE THREAD

**Issue by pritishmishra** [cloudfoundry-incubator/haproxy-boshrelease#101]
Hi guys

I am part of Service-Fabrik Broker team. It is also a CloudFoundry-incubated project.
Currently, we are evaluating the usage of Keepalived in our project, which is also a CloudFoundry-incubated project.

We had concern regarding licensing. Our project has an Apache License 2.0, quite similar to haproxy-boshrelease. However, since, Keepalived uses a GNU General Public License v2.0, we were unsure how to go forward about using it for our project.

Can you please let us know how you solved this issue? Did you do any legal consultations and found that it is fine? Since, you have been using the package for a long time now, we felt, your feedback could be extremely helpful.

Thanks!

**Comment by kamath-prasad** [comment]
@axelfauvel : can you please let us know ?

**Comment by axelfauvel** [comment]
Hey guys,

AFAIK, GNU GPL authorizes execution, modification and redistribution of source code without copyright whereas Apache License forces the contributor to preserve the copyright.
From what I can read, GNU is a more permissive licence than Apache so it shouldn't be a problem to use GNU GPL licensed program in an Apache license project.

I'm not a legal consultant though, just a wikipedia reader :)

**Comment by pritishmishra** [comment]
Thanks @axelfauvel for your feedback!
