### ISSUE TITLE
How to configure custom http fronted and backend

### ISSUE THREAD

**Issue by Alexvianet** [cloudfoundry-incubator/haproxy-boshrelease#103]
I need such configuration, how to handle it with current manifest ?

```
frontend html
bind _:8200 ssl crt _your_cert_stack* ciphers your_cipher_list
default_backend vaultsrvs

backend vaultsrvs
mode http
option httpchk GET /v1/sys/health HTTP/1.1
balance roundrobin
http-check expect status 200
server vaultmaster check ssl verify
server vaultslave check ssl verify
```

**Comment by gdenn** [comment]
hi Alexvianet,

there is no need to create another frontend for this. HAProxy can forward to multiple backends from a single frontend via ACL rules and use different SSL certs through SNI.

Define your backend with `ha_proxy.routed_backend_servers` (@checkout https://github.com/cloudfoundry-incubator/haproxy-boshrelease/blob/master/jobs/haproxy/templates/haproxy.config.erb#L255-L259). Use `ha_proxy.crt_list` to use SNI. You can even configure custom ciphers.

best,
D

**Comment by Alexvianet** [comment]
For now we use raw config and it's helpd
