### ISSUE TITLE
send-proxy for tcp backends

### ISSUE THREAD

**Issue by poblin-orange** [cloudfoundry-incubator/haproxy-boshrelease#119]
We are using haproxy bosh release tcp loadbalancing feature. Out of the box, the originating ip is lost, the backend http server only sees haproxy as originating ip.

To solve this, haproxy has a send-proxy clause on the tcp backend members, propagating the originating ip.

**Comment by geofffranks** [comment]
Is this just on tcp backends? Is this using the CF tcp-router's link for the haproxy frontend/backend, or an explicit configuration in the haproxy properties?

Happy to receive a PR on this, as I don't have an environment that makes use of all these features for testing.

**Comment by poblin-orange** [comment]
@geofffranks  yes only for tcp backend, when using haproxy bosh release as level 2 relay (we let downstream servers handle ssl offload, but we need to keep the originating ip)

**Comment by geofffranks** [comment]
@poblin-orange I vaguely remember someone at orange submitting a PR for this. Is this still an issue?
