### ISSUE TITLE
multiple protected domain rules

### ISSUE THREAD

**Issue by shalako** [cloudfoundry-incubator/haproxy-boshrelease#120]
Currently this release supports a list of domains, and a list of cidrs. Presumably all specified domains are protected, and accessible from all specified cidrs.

https://github.com/cloudfoundry-incubator/haproxy-boshrelease/blob/master/jobs/haproxy/spec#L58-L63

I have a customer who wants the following rules:
1. `public.com` should be accessible only from <cidr for WAF>
2. `private.com` should be accessible only from <cidr for private network>
3. `public.com` should not be accessible from private network, and `private.com` should not be accessible from WAF

This seems like an array of protected domains and their whitelisted cidrs.

**Comment by geofffranks** [comment]
Doesn’t look like this is currently possible, but it sounds like adding negation support to the acls defined in ha_proxy.http_request_deny_conditions might solve it in a more general-purpose way. Does that seem accurate?

**Comment by geofffranks** [comment]
Negation support was recently added to `ha_proxy.http_request_deny_conditions`, which should allow these behaviors now
