### ISSUE TITLE
How to move haproxy logs to haproxy directory

### ISSUE THREAD

**Issue by Alexvianet** [cloudfoundry-incubator/haproxy-boshrelease#128]
we have all haproxy logs in monit/ directory:

```
haproxy/8bf13517-0132-4e58-8d47-325d96e19843:/var/vcap/sys/log# ls
haproxy  keepalived  monit
haproxy/8bf13517-0132-4e58-8d47-325d96e19843:/var/vcap/sys/log# ls haproxy/
haproxy/8bf13517-0132-4e58-8d47-325d96e19843:/var/vcap/sys/log# ls monit/
haproxy.err.log  haproxy.log  monit_debugger.haproxy_ctl.log

```
how to store it correctly?

**Comment by geofffranks** [comment]
haproxy logs via syslog currently, so anything other than startup logs are going to be in /var/log/messages (or wherever the local syslog config is sending them). There's a commit on master that hasn't been released yet which converts haproxy over to starting via BPM, which moves its startup logs into /var/log/haproxy. Hopefully I'll have some time tomorrow to test + release it
