### ISSUE TITLE
haproxy_wrapper script has syntax errors

### ISSUE THREAD

**Issue by domdom82** [cloudfoundry-incubator/haproxy-boshrelease#140]
The wrapper script for BPM has the following errors:

- Bash syntax error in line 13: 
  `/var/vcap/jobs/haproxy/bin/haproxy_wrapper: line 13: -f: command not found`
- Script will exit (`set -e`) if pid can no longer be found (pkill will exit 1)

Opened PR #139 to fix this.

**Comment by geofffranks** [comment]
Fixed via #139
