### ISSUE TITLE
hatop no longer works with python3 stemcells

### ISSUE THREAD

**Issue by domdom82** [cloudfoundry-incubator/haproxy-boshrelease#160]
Latest stemcells (xenial-go_agent/621.55) use python3 only and have removed python 2.7.x

This breaks hatop until https://github.com/feurix/hatop/pull/7 is merged and pulled into this repo.

I am not really sure if hatop is still alive, last commit was in 2015...

We should either fork it or remove it because atm it is useless.

**Comment by geofffranks** [comment]
@jhunt any desire to fork + maintain hatop around given the lack of python 2.7 in new stemcells, or can we just remove it from the boshrelease?

**Comment by jhunt** [comment]
Yeah, I'll fork it and maintain it; I depend on it far too much (outside of even this BOSH release) to let it die on the vine.

I've forked it over to https://github.com/jhunt/hatop, and will merge in the Python3 support and take it for a spin.
