### ISSUE TITLE
v9.8.0 does not contain haproxy v1.9.11

### ISSUE THREAD

**Issue by jebreuer** [cloudfoundry-incubator/haproxy-boshrelease#164]
While using v9.8.0 (`Latest commit 514038d on 29 Feb`) I noticed that I could not use features of haproxy v1.9.11.

I bosh ssh'd into a deployed instance and executed:
```
# /var/vcap/packages/haproxy/bin/haproxy -v
HA-Proxy version 1.8.20 2019/04/25
Copyright 2000-2019 Willy Tarreau <willy@haproxy.org>
```
It shows that v1.8.20 is bundled in the v9.8.0 BOSHrelease.

However, when manually creating a dev release and using that one (`bosh create-release && bosh upload-release && ./deploy`) it shows:
```
# /var/vcap/packages/haproxy/bin/haproxy -v
HA-Proxy version 1.9.11 2019/09/27 - https://haproxy.org/
```
Here it answers with the correct version number.

I'd assume that the current final is broken but that could be resolved by just creating a new proper final based on the current master since the blobs seem to be correctly configured.

EDIT:
This is the broken final that I used:
```
url: https://github.com/cloudfoundry-incubator/haproxy-boshrelease/releases/download/v9.8.0/haproxy-9.8.0.tgz
sha1: 8b9bf30e11e19f40e88cafa1a3cca1037f350516
```

**Comment by geofffranks** [comment]
There has not been a final released published since 9.8.0, which was released prior to updating the blobs. Should be one soon though.
