### ISSUE TITLE
Improve FORWARD SECRECY

### ISSUE THREAD

**Issue by lcacciagioni** [cloudfoundry-incubator/haproxy-boshrelease#48]
The creation of TLS session tickets is today supposing a big security risk, for that reason to improve Perfect Forward Secrecy is recommended to disable SSL session tickets. For that reason I'll recommend to add (Maybe as an alternative) the flag `no-tls-tickets` (Alongside the no-sslv3) in all the places where you have ssl configs.
You can find a simple explanation [here](https://timtaubert.de/blog/2014/11/the-sad-state-of-server-side-tls-session-resumption-implementations/)

**Comment by geofffranks** [comment]
@christopherclark Is it possible to disable the above bot integration, since we don't have a tracker project for this repo?

**Comment by geofffranks** [comment]
@lcacciagioni I'm in favor of this, but probably won't be able to dedicate time to it for a little bit. If you need this sooner, feel free to submit a PR adding support for this (configurable, but defaulting to enabled would be awesome). 

Thanks!

**Comment by lcacciagioni** [comment]
Sure I'll take a look tonight and add it. BTW PR from fork or branch? Because I don't see any guidelines on how to contribute.

Thanks!

**Comment by geofffranks** [comment]
Probably a fork, unless you're a member of the cloudfoundry-incubator org. You'll also need to sign the CloudFoundry Org's CLA, but there should be a bot for helping you out with that (if you haven't already), when you submit the PR.
