### ISSUE TITLE
HSTS Support

### ISSUE THREAD

**Issue by lcacciagioni** [cloudfoundry-incubator/haproxy-boshrelease#49]
I think it could be really good to improve the ssl security to force the [HSTS](https://www.owasp.org/index.php/HTTP_Strict_Transport_Security_Cheat_Sheet) header from haproxy which normally will be the place to do ssl offloading.
We can add this as an extra.

> Curious is that many times I have only achieved an `A+` in ssllabs test after enabling HSTS and in your config this is not an option.

**Comment by mkb** [comment]
Agree 100% that HSTS is a good thing. Forcing HSTS will break some sites so better to make HSTS a configurable option.

There's are good arguments either way for defaulting to off vs on. So long as HSTS is configurable and visible either default is fine.

**Comment by geofffranks** [comment]
@lcacciagioni Same story as #48, if you want to submit a PR :)
