### ISSUE TITLE
Error deploying haproxy v8.1.1

### ISSUE THREAD

**Issue by Martin612** [cloudfoundry-incubator/haproxy-boshrelease#57]
Hello,

I want to deploy the haproxy-boshrelease in an openstack-environment.
First I set up bosh and uploaded the haproxy-boshrelease 8.1.1.
When I try to deploy I get the following error:

Error 100: Unable to render instance groups for deployment. Errors are:
   - Unable to render jobs for instance group 'haproxy'. Errors are:
     - Unable to render templates for job 'haproxy'. Errors are:
       - Error filling in template '(unknown)' (line (unknown): haproxy/haproxy.config.erb:214: syntax error, unexpected ';'
      ...ch_with_index do |ip, index| -; _erbout.concat "\n        se...
      ...                               ^
      haproxy/haproxy.config.erb:215: syntax error, unexpected ';'
      ...f_p("ha_proxy.resolvers") do -; _erbout.concat "\n        re...

If I'm using an older version (8.0.12), the deployment finishes successfully.

How can I configure my environment to use the latest haproxy-boshrelease?

Best regards,
Martin

**Comment by geofffranks** [comment]
I'm not seeing that error when I deploy v8.1.1. Also, those line numbers don't match up with what's on master + the 8.1.1 release, which is a little confusing.

Any chance you could send me your manifest?

**Comment by Martin612** [comment]
I attach the manifest, the error output and the haproxy.config.erb file from v8.1.1 release.

From my point of view this line numbers seems to match with the v8.1.1 release.

Did you need more information?

[haproxy_error.zip](https://github.com/cloudfoundry-incubator/haproxy-boshrelease/files/1011280/haproxy_error.zip)

**Comment by geofffranks** [comment]
Your manifest works fine for me. Out of curiosity, what version of the BOSH director are you using? I wonder if the problem is related to the `-%>` syntax.

**Comment by geofffranks** [comment]
@Martin612 are you still having this issue?

**Comment by Martin612** [comment]
I wasn't able to deploy the ha-proxy release on bosh(version: 259.0.0 cli: 1.3262.26.0).

After setting up a new bosh(version: 261.4 cli: 2.0.16) my manifest work with the ha-proxy release 8.1.1.
Therefore the error have to be related to the bosh version.

Thank you.
