### ISSUE TITLE
Where does the ttar blob come from?

### ISSUE THREAD

**Issue by ryanmoran** [cloudfoundry-incubator/haproxy-boshrelease#75]

**Comment by geofffranks** [comment]
It's a custom script, that should probably be in src, rather than the blobs dir. I'll try to get that moved over soon

**Comment by jhunt** [comment]
https://github.com/jhunt/ttar

**Comment by kdykeman** [comment]
Any chance of adding a license declaration to that repo?

**Comment by geofffranks** [comment]
Converted ttar into a submodule for haproxy for more clarity. @kdykeman can you open an issue on the official ttar repo for the license?
