### ISSUE TITLE
Why do all the logs for this show up in the `/var/vcap/sys/log/monit/` sub-directory?

### ISSUE THREAD

**Issue by jhunt** [cloudfoundry-incubator/haproxy-boshrelease#81]
The `/var/vcap/sys/log/haproxy/` directory exists, but is empty.

**Comment by jhunt** [comment]
Had a bad TLS certificate (malformed PEM) that was causing haproxy to choke, and couldn't find anything useful until we looked in the monit debug log.  Is it possible that start up messages go to stdout/stderr and that's not being handled properly (i.e. `>> $LOG_DIR/haproxy.log 2>&`)?

I'll try to get the monit debugging log some time later today, for evidence.

Also, it would be nice to print a message that haproxy logs to syslog, to assist operators troubleshooting...

**Comment by jhunt** [comment]
Here's what we found in `/var/vcap/sys/log/monit/haproxy.err.log`:

```
ls: cannot access /var/vcap/packages/*/lib: No such file or directory
ls: cannot access /var/vcap/packages/*/*/*.jar: No such file or directory
/var/vcap/jobs/haproxy/config/ssl/cert-0.pem
[ALERT] 271/195804 (2514) : Proxy 'http-routers', server 'node0' [/var/vcap/jobs/haproxy/config/haproxy.config:118] unable to load CA file '/var/vcap/jobs/haproxy/config/backend-ca-certs.pem'.
[ALERT] 271/195804 (2514) : Proxy 'http-routers', server 'node1' [/var/vcap/jobs/haproxy/config/haproxy.config:119] unable to load CA file '/var/vcap/jobs/haproxy/config/backend-ca-certs.pem'.
[ALERT] 271/195804 (2514) : Proxy 'http-routers', server 'node2' [/var/vcap/jobs/haproxy/config/haproxy.config:120] unable to load CA file '/var/vcap/jobs/haproxy/config/backend-ca-certs.pem'.
[WARNING] 271/195804 (2514) : parsing [/var/vcap/jobs/haproxy/config/haproxy.config:26] : 'option httplog' not usable with frontend 'tcp-frontend_diego_brain' (needs 'mode http'). Falling back to 'option tcplog'.
[WARNING] 271/195804 (2514) : config : 'option forwardfor' ignored for frontend 'tcp-frontend_diego_brain' as it requires HTTP mode.
[WARNING] 271/195804 (2514) : config : 'option forwardfor' ignored for backend 'tcp-diego_brain' as it requires HTTP mode.
[ALERT] 271/195804 (2514) : Fatal errors found in configuration.
Fri Sep 29 19:58:04 UTC 2017: Errored starting HAProxy
```

As a user and an operator, I would like to see this error message in `/var/vcap/sys/log/haproxy/haproxy.log`, alongside a message like `haproxy logs most of its output to syslog; check /var/log/messages for details`

**Comment by jhunt** [comment]
Is this fix something that this project is interested in pursuing?

**Comment by geofffranks** [comment]
Absolutely

**Comment by geofffranks** [comment]
Converted haproxy to start via BPM, which moves its startup logs into /var/vcap/sys/log/haproxy, and should resolve this. Should be released later this week
