### ISSUE TITLE
Blacklist domains

### ISSUE THREAD

**Issue by shalako** [cloudfoundry-incubator/haproxy-boshrelease#84]
Hi @geofffranks 
Could you expose a property that list of domains for which HAProxy rejects requests (blacklist)?

Given a load balancer on the internet to which DNS resolves the CF app domain
And the operator does not want to ask the IT team to configure that LB to reject requests for the system domain, or to filter on host header
And the operator can't be sure that firewall rules would prevent Gorouter from forwarding requests with a spoofed host header to Cloud Controller and UAA
When I send a request to the app domain with a host header for `api.sys-domain.cf.com`
I expect to receive a 403-type error

This would improve security for operators attempting to protect the system domain.

Let me know if you'd prefer a PR.

Thank you!

**Comment by geofffranks** [comment]
Would ha_proxy.internal_only_domains and
ha_proxy.trusted_domain_cidrs solve this?

**Comment by shalako** [comment]
Hi Geoff,

I think of those two properties as a whitelist. A blacklist would be a list of domains for which the proxy would reject requests. 

The two existing properties fulfill the use case of accepting requests for specified domains only if the origin is trusted. 

We want to reject requests for a specified list of domains. 

Thanks!

**Comment by geofffranks** [comment]
Anything in the list of internal domains is rejected unless the request was originating from one of the trusted cidr blocks. It's there specifically for blocking internet traffic to internal domains. If you don't want anything getting through to that domain, you could use internal only domains with no trusted cidrs.

How are the domains you're trying to blacklist being reached? A separate set of load balancers that circumvent haproxy?

**Comment by geofffranks** [comment]
Seems like this can be handled now via the `ha_proxy.http_deny_request` property
