### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by acrmp** [cloudfoundry-incubator/haproxy-boshrelease#85]
There are a number of recent changes on `master` that it would be great to have in a released version. In particular we'd love to see the mutual ssl changes in a release.

Would you be able to cut a new release soon?

Thanks,

Andrew.

**Comment by geofffranks** [comment]
I'm hoping to have a new CI environment up in the next few days and should be able to get the new stuff released soon

**Comment by geofffranks** [comment]
https://github.com/cloudfoundry-incubator/haproxy-boshrelease/releases/tag/v8.4.2 is out finally
